name: Move Tag to Latest Commit

on:
  push:
    branches:
      - main  

jobs:
  retag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Move tag to current commit
        run: |
          git config --global Feriel080 "GitHub Actions"
          
          # Force-move the tag (deletes old, creates new)
          git tag -f v1.0
          git push origin v1.0 --force